AppointmentScheduling/Controllers/AppointmentController.cs
using AppointmentScheduling.Services;
using AppointmentScheduling.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppointmentScheduling.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _appointmentService;

        public AppointmentController(IAppointmentService appointmentService)
        {
            _appointmentService = appointmentService;
        }

        public IActionResult Index()
        {
            ViewBag.DoctorList = _appointmentService.GetDoctorList();
            ViewBag.PatientList = _appointmentService.GetPatientList();
            ViewBag.Duration = Helper.GetTimeDropDown();
            return View();
        }
    }
}

AppointmentScheduling/Views/Shared/_AddEditAppointment.cshtml
<div class="modal fade" role="dialog" id="appointmentInput" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="appointmentForm" autocomplete="off" novalidate="novalidate">
                <div class="modal-header">
                    @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Admin))
                    {
                        <h4 class="modal-title">Add/Edit Appointment</h4>
                    }
                    else
                    {
                        <h4 class="modal-title">Appointment Details</h4>
                    }
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" maxlength="100" class="form-control" id="title" />
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea type="text" class="form-control" id="description"></textarea>
                    </div>
                    @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Admin))
                    {
                        <div class="form-group">
                            <label for="patientId">Select Patient:</label>
                            <select id="patientId" asp-items="@(new SelectList(ViewBag.PatientList, "Id", "Name"))" class="form-control"></select>
                        </div>
                    }
                    else
                    {
                        @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Doctor))
                        {
                            <div class="form-group">
                                <label for="lblPatientName">Patient Name</label>
                                <label disabled id="lblPatientName" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="lblStatus">Status</label>
                                <label disabled id="lblStatus" class="form-control" />
                            </div>
                        }

                        @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Patient))
                        {
                            <div class="form-group">
                                <label for="lblDoctorName">Doctor Name</label>
                                <label disabled id="lblDoctorName" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="lblStatus">Status</label>
                                <label disabled id="lblStatus" class="form-control" />
                            </div>
                        }

                    }
                    <div class="form-group">
                        <label for="appointmentDate">Start Date Time</label>
                        <input id="appointmentDate" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="duration">Duration:</label>
                        <select id="duration" asp-items="ViewBag.Duration" class="form-control"></select>
                    </div>
                    <input type="hidden" id="id" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" onclick="onCloseModal();">Close</button> &nbsp;

                    @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Admin))
                    {
                        <button type="button" id="btnSubmit" class="btn btn-success" onclick="onSubmitForm();">Submit</button>
                        <button type="button" id="btnDelete" class="btn btn-danger" onclick="onDeleteAppointment();">Delete</button>

                    }

                    @if (User.IsInRole(AppointmentScheduling.Utility.Helper.Doctor))
                    {
                        <button type="button" id="btnConfirm" class="btn btn-success" onclick="onConfirm();">Confirm</button>
                        <button type="button" id="btnDelete" class="btn btn-danger" onclick="onDeleteAppointment();">Delete</button>

                    }

                </div>
            </form>
        </div>
    </div>
</div>

AppointmentScheduling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppointmentScheduling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2020.2.513/styles/kendo.default-v2.min.css" />
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Appointment" asp-action="Index">Appointments</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppointmentScheduling - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/select2/js/select2.full.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.513/js/kendo.all.min.js"></script>
    <script type="text/javascript" src="~/js/notify.min.js"></script>
    <script src="~/js/script-custom-calendar.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>